# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/uni/PEI/decoys/MainWindow.ui'
#
# Created: Sun Jul 24 01:27:04 2011
#      by: pyside-uic 0.2.11 running on PySide 1.0.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.kdecoysCheckBox = QtGui.QCheckBox(self.tabWidgetPage1)
        self.kdecoysCheckBox.setObjectName("kdecoysCheckBox")
        self.verticalLayout_5.addWidget(self.kdecoysCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtGui.QLabel(self.tabWidgetPage1)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 14, -1, 14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.addQueryButton = QtGui.QPushButton(self.tabWidgetPage1)
        self.addQueryButton.setObjectName("addQueryButton")
        self.horizontalLayout_6.addWidget(self.addQueryButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.clearActives = QtGui.QPushButton(self.tabWidgetPage1)
        self.clearActives.setObjectName("clearActives")
        self.horizontalLayout_6.addWidget(self.clearActives)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.queryList = QtGui.QListWidget(self.tabWidgetPage1)
        self.queryList.setObjectName("queryList")
        self.verticalLayout.addWidget(self.queryList)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.kdecoysFrame = QtGui.QFrame(self.tabWidgetPage1)
        self.kdecoysFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.kdecoysFrame.setLineWidth(0)
        self.kdecoysFrame.setObjectName("kdecoysFrame")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.kdecoysFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(self.kdecoysFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 14, -1, 14)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.addDecoysButton = QtGui.QPushButton(self.kdecoysFrame)
        self.addDecoysButton.setObjectName("addDecoysButton")
        self.horizontalLayout_9.addWidget(self.addDecoysButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.clearDecoys = QtGui.QPushButton(self.kdecoysFrame)
        self.clearDecoys.setObjectName("clearDecoys")
        self.horizontalLayout_9.addWidget(self.clearDecoys)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.decoyList = QtGui.QListWidget(self.kdecoysFrame)
        self.decoyList.setObjectName("decoyList")
        self.verticalLayout_6.addWidget(self.decoyList)
        self.horizontalLayout.addWidget(self.kdecoysFrame)
        self.line = QtGui.QFrame(self.tabWidgetPage1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zinclabel = QtGui.QLabel(self.tabWidgetPage1)
        self.zinclabel.setEnabled(False)
        self.zinclabel.setObjectName("zinclabel")
        self.horizontalLayout_3.addWidget(self.zinclabel)
        self.zsubComboBox = QtGui.QComboBox(self.tabWidgetPage1)
        self.zsubComboBox.setEnabled(False)
        self.zsubComboBox.setObjectName("zsubComboBox")
        self.horizontalLayout_3.addWidget(self.zsubComboBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.cacheCheckBox = QtGui.QCheckBox(self.tabWidgetPage1)
        self.cacheCheckBox.setEnabled(False)
        self.cacheCheckBox.setChecked(True)
        self.cacheCheckBox.setObjectName("cacheCheckBox")
        self.horizontalLayout_3.addWidget(self.cacheCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dbComboBox = QtGui.QComboBox(self.tabWidgetPage1)
        self.dbComboBox.setObjectName("dbComboBox")
        self.dbComboBox.addItem("")
        self.dbComboBox.addItem("")
        self.dbComboBox.addItem("")
        self.dbComboBox.addItem("")
        self.dbComboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.dbComboBox)
        self.addDButton = QtGui.QPushButton(self.tabWidgetPage1)
        self.addDButton.setObjectName("addDButton")
        self.horizontalLayout_8.addWidget(self.addDButton)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.clearDB = QtGui.QPushButton(self.tabWidgetPage1)
        self.clearDB.setObjectName("clearDB")
        self.horizontalLayout_8.addWidget(self.clearDB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.dbListWidget = QtGui.QListWidget(self.tabWidgetPage1)
        self.dbListWidget.setObjectName("dbListWidget")
        self.verticalLayout_2.addWidget(self.dbListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.outDirButton = QtGui.QPushButton(self.tabWidgetPage1)
        self.outDirButton.setObjectName("outDirButton")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.outDirButton)
        self.outputDirectoryLineEdit = QtGui.QLineEdit(self.tabWidgetPage1)
        self.outputDirectoryLineEdit.setObjectName("outputDirectoryLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.outputDirectoryLineEdit)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.resultsTable = QtGui.QTableWidget(self.tab)
        self.resultsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultsTable.setAlternatingRowColors(True)
        self.resultsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(7)
        self.resultsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(6, item)
        self.resultsTable.verticalHeader().setSortIndicatorShown(True)
        self.resultsTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.resultsTable, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.informationSavedToLabel = QtGui.QLabel(self.tab)
        self.informationSavedToLabel.setObjectName("informationSavedToLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.informationSavedToLabel)
        self.informationSavedToLineEdit = QtGui.QLineEdit(self.tab)
        self.informationSavedToLineEdit.setReadOnly(True)
        self.informationSavedToLineEdit.setObjectName("informationSavedToLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.informationSavedToLineEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._3 = QtGui.QFormLayout()
        self._3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self._3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._3.setFormAlignment(QtCore.Qt.AlignCenter)
        self._3.setObjectName("_3")
        self.tanimotoCutoffLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.tanimotoCutoffLabel.setObjectName("tanimotoCutoffLabel")
        self._3.setWidget(0, QtGui.QFormLayout.LabelRole, self.tanimotoCutoffLabel)
        self.tanimotoBox = QtGui.QDoubleSpinBox(self.tabWidgetPage2)
        self.tanimotoBox.setMaximum(1.0)
        self.tanimotoBox.setSingleStep(0.1)
        self.tanimotoBox.setObjectName("tanimotoBox")
        self._3.setWidget(0, QtGui.QFormLayout.FieldRole, self.tanimotoBox)
        self.decoyDecoyTanimotoLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.decoyDecoyTanimotoLabel.setObjectName("decoyDecoyTanimotoLabel")
        self._3.setWidget(1, QtGui.QFormLayout.LabelRole, self.decoyDecoyTanimotoLabel)
        self.dTanimotoBox = QtGui.QDoubleSpinBox(self.tabWidgetPage2)
        self.dTanimotoBox.setMaximum(1.0)
        self.dTanimotoBox.setSingleStep(0.1)
        self.dTanimotoBox.setObjectName("dTanimotoBox")
        self._3.setWidget(1, QtGui.QFormLayout.FieldRole, self.dTanimotoBox)
        self.hBALabel_2 = QtGui.QLabel(self.tabWidgetPage2)
        self.hBALabel_2.setObjectName("hBALabel_2")
        self._3.setWidget(3, QtGui.QFormLayout.LabelRole, self.hBALabel_2)
        self.hbaBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.hbaBox.setObjectName("hbaBox")
        self._3.setWidget(3, QtGui.QFormLayout.FieldRole, self.hbaBox)
        self.hBDLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.hBDLabel.setObjectName("hBDLabel")
        self._3.setWidget(4, QtGui.QFormLayout.LabelRole, self.hBDLabel)
        self.hbdBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.hbdBox.setObjectName("hbdBox")
        self._3.setWidget(4, QtGui.QFormLayout.FieldRole, self.hbdBox)
        self.molecularWeightLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.molecularWeightLabel.setObjectName("molecularWeightLabel")
        self._3.setWidget(5, QtGui.QFormLayout.LabelRole, self.molecularWeightLabel)
        self.molwtBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.molwtBox.setMaximum(999)
        self.molwtBox.setObjectName("molwtBox")
        self._3.setWidget(5, QtGui.QFormLayout.FieldRole, self.molwtBox)
        self.rtotationalBondsLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.rtotationalBondsLabel.setObjectName("rtotationalBondsLabel")
        self._3.setWidget(6, QtGui.QFormLayout.LabelRole, self.rtotationalBondsLabel)
        self.rotbBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.rotbBox.setObjectName("rotbBox")
        self._3.setWidget(6, QtGui.QFormLayout.FieldRole, self.rotbBox)
        self.clogPLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.clogPLabel.setObjectName("clogPLabel")
        self._3.setWidget(7, QtGui.QFormLayout.LabelRole, self.clogPLabel)
        self.clogpBox = QtGui.QDoubleSpinBox(self.tabWidgetPage2)
        self.clogpBox.setSingleStep(0.1)
        self.clogpBox.setObjectName("clogpBox")
        self._3.setWidget(7, QtGui.QFormLayout.FieldRole, self.clogpBox)
        self.maximumDecoysPerActiveLigandLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.maximumDecoysPerActiveLigandLabel.setObjectName("maximumDecoysPerActiveLigandLabel")
        self._3.setWidget(9, QtGui.QFormLayout.LabelRole, self.maximumDecoysPerActiveLigandLabel)
        self.decoyMaxSpinBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.decoyMaxSpinBox.setMaximum(99999)
        self.decoyMaxSpinBox.setObjectName("decoyMaxSpinBox")
        self._3.setWidget(9, QtGui.QFormLayout.FieldRole, self.decoyMaxSpinBox)
        self.decoyLimitLabel = QtGui.QLabel(self.tabWidgetPage2)
        self.decoyLimitLabel.setObjectName("decoyLimitLabel")
        self._3.setWidget(10, QtGui.QFormLayout.LabelRole, self.decoyLimitLabel)
        self.decoyMinSpinBox = QtGui.QSpinBox(self.tabWidgetPage2)
        self.decoyMinSpinBox.setMaximum(99999)
        self.decoyMinSpinBox.setObjectName("decoyMinSpinBox")
        self._3.setWidget(10, QtGui.QFormLayout.FieldRole, self.decoyMinSpinBox)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._3.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem11)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._3.setItem(8, QtGui.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._3.setItem(2, QtGui.QFormLayout.FieldRole, spacerItem13)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._3.setItem(8, QtGui.QFormLayout.FieldRole, spacerItem14)
        self.verticalLayout_3.addLayout(self._3)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.cacheButton = QtGui.QPushButton(self.tabWidgetPage2)
        self.cacheButton.setObjectName("cacheButton")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.cacheButton)
        self.cachDirectoryLineEdit = QtGui.QLineEdit(self.tabWidgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cachDirectoryLineEdit.sizePolicy().hasHeightForWidth())
        self.cachDirectoryLineEdit.setSizePolicy(sizePolicy)
        self.cachDirectoryLineEdit.setObjectName("cachDirectoryLineEdit")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.cachDirectoryLineEdit)
        self.verticalLayout_3.addLayout(self.formLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.defaultsButton = QtGui.QPushButton(self.tabWidgetPage2)
        self.defaultsButton.setObjectName("defaultsButton")
        self.horizontalLayout_7.addWidget(self.defaultsButton)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName("_2")
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self._2.addWidget(self.clearButton)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem17)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self._2.addWidget(self.stopButton)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem18)
        self.findDecoysButton = QtGui.QPushButton(self.centralwidget)
        self.findDecoysButton.setObjectName("findDecoysButton")
        self._2.addWidget(self.findDecoysButton)
        self.verticalLayout_4.addLayout(self._2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.tanimotoCutoffLabel.setBuddy(self.kdecoysFrame)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.progressBar.reset)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.statusbar.clearMessage)
        QtCore.QObject.connect(self.clearDecoys, QtCore.SIGNAL("clicked()"), self.decoyList.clear)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.decoyList.clear)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.dbListWidget.clear)
        QtCore.QObject.connect(self.clearDB, QtCore.SIGNAL("clicked()"), self.dbListWidget.clear)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.queryList.clear)
        QtCore.QObject.connect(self.clearActives, QtCore.SIGNAL("clicked()"), self.queryList.clear)
        QtCore.QObject.connect(self.kdecoysCheckBox, QtCore.SIGNAL("toggled(bool)"), self.kdecoysFrame.setVisible)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), self.informationSavedToLineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DecoyFinder", None, QtGui.QApplication.UnicodeUTF8))
        self.kdecoysCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Add new decoys to an existing decoy set", None, QtGui.QApplication.UnicodeUTF8))
        self.kdecoysCheckBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Add new decoys to an existing decoy set", None, QtGui.QApplication.UnicodeUTF8))
        self.kdecoysCheckBox.setText(QtGui.QApplication.translate("MainWindow", "  Add new decoys", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "Add here at least one file containing the active ligands you would like to find decoys for", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Add here at least one file containing the active ligands you would like to find decoys for", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Known Active Ligands", None, QtGui.QApplication.UnicodeUTF8))
        self.addQueryButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose one or more files to add to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.addQueryButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.clearActives.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove all items from this list", None, QtGui.QApplication.UnicodeUTF8))
        self.clearActives.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("MainWindow", "Add here files containing decoy molecules for the chosen active ligands. These molecules will be directly accepted as decoys and will be included in the final output file. This is suitable for example to complete a decoy set. Decoy molecules from this list will only be taken into account during the search for decoy vs decoy tanimoto thresholds.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Add here files containing decoy molecules for the chosen active ligands. These molecules will be directly accepted as decoys and will be included in the final output file. This is suitable, for example, to complete a decoy set. Decoy molecules from this list will only be taken into account during the search for decoy vs decoy tanimoto thresholds.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Existing Decoy files", None, QtGui.QApplication.UnicodeUTF8))
        self.addDecoysButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose one or more files to add to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.addDecoysButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDecoys.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove all items from this list", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDecoys.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Where you can choose where to look for new decoys", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Where you can choose where to look for new decoys", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sources of new Decoys", None, QtGui.QApplication.UnicodeUTF8))
        self.zinclabel.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose the ZINC subset (by property) to use as source. They are described at <a href=\"http://zinc.docking.org/subset1/\"><span style=\" text-decoration: underline; color:#0057ae;\">http://zinc.docking.org/subset1/</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.zinclabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose the ZINC subset (by property) to use as source. They are described <a href=\"http://zinc.docking.org/subset1/\"><span style=\" text-decoration: underline; color:#0057ae;\">here</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.zinclabel.setText(QtGui.QApplication.translate("MainWindow", "ZINC subset:", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to be able to look for decoys through the ZINC database, DecoyFinder needs to download little chunks of it and then remove them. If this option is enabled, DecoyFinder will not remove them and so will not need to download already downloaded files again.<br />Enable this if you have low bandwith and/or +20 GB of free disk space.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheCheckBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to be able to look for decoys through the ZINC database, DecoyFinder needs to download little chunks of it and then remove them. If this option is enabled, DecoyFinder will not remove them and so will not need to download already downloaded files again.<br />Enable this if you have low bandwith and/or +20 GB of free disk space.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Use caché", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here you can select the kind of source you want to add:<br />- Local files: files containing molecules located in the filesystem</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- ZINC subset: use file from ZINC from either of these pH range subsets: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - usual: usual pH range (5.75-8.25)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - metal: for metalloenzymes (usual + pH 7-9.5)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - single: contains only a single form of each molecule</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - all: contains the whole pH range (4.5-9.5)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here you can select the kind of source you want to add:<br />- Local files: files containing molecules located in the filesystem</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- ZINC subset: use file from ZINC from either of these pH range subsets: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - usual: usual pH range (5.75-8.25)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - metal: for metalloenzymes (usual + pH 7-9.5)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - single: contains only a single form of each molecule</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - all: contains the whole pH range (4.5-9.5)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select local files...", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "ZINC single", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "ZINC metals", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "ZINC usual", None, QtGui.QApplication.UnicodeUTF8))
        self.dbComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "ZINC all", None, QtGui.QApplication.UnicodeUTF8))
        self.addDButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDB.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove all items from this list", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDB.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.outDirButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose the name of the file where found decoys are going to be saved", None, QtGui.QApplication.UnicodeUTF8))
        self.outDirButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Choose the name of the file where found decoys are going to be saved", None, QtGui.QApplication.UnicodeUTF8))
        self.outDirButton.setText(QtGui.QApplication.translate("MainWindow", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Decoys found", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "HBA", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "HBD", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "logP", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "M. weight", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Rot. bonds", None, QtGui.QApplication.UnicodeUTF8))
        self.informationSavedToLabel.setText(QtGui.QApplication.translate("MainWindow", "This information can be found at", None, QtGui.QApplication.UnicodeUTF8))
        self.informationSavedToLineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "This file is intended to be open as a spreadsheet, preferably with Calc, Excel, Gnumeric or a similar application.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Run Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.tanimotoCutoffLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Here you can set the maximum Tanimoto value between a decoy molecule and its respective active ligand. The lower the value, the more chemically different will be the accepted decoys.", None, QtGui.QApplication.UnicodeUTF8))
        self.tanimotoCutoffLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Here you can set the maximum Tanimoto value between a decoy molecule and its respective active ligand. The lower the value, the more chemically different will be the accepted decoys.", None, QtGui.QApplication.UnicodeUTF8))
        self.tanimotoCutoffLabel.setText(QtGui.QApplication.translate("MainWindow", "Active ligand vs Decoy Tanimoto threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyDecoyTanimotoLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Here you can set the maximum Tanimoto value between decoys. This is useful to get a set of chemically different decoys. The lower the value, the more chemically different will be the accepted decoys. When set to 1.00, decoy vs decoy tanimoto calculation will be skipped.", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyDecoyTanimotoLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Here you can set the maximum Tanimoto value between decoys. This is useful to get a set of chemically different decoys. The lower the value, the more chemically different will be the accepted decoys. When set to 1.00, decoy vs decoy tanimoto calculation will be skipped.", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyDecoyTanimotoLabel.setText(QtGui.QApplication.translate("MainWindow", "Decoy vs Decoy Tanimoto threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.hBALabel_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of HBA of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of HBA in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.hBALabel_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of HBA of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of HBA in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.hBALabel_2.setText(QtGui.QApplication.translate("MainWindow", "Hydrogen Bond Acceptors ±", None, QtGui.QApplication.UnicodeUTF8))
        self.hBDLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of HBD of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of HBD in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.hBDLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of HBD of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of HBD in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.hBDLabel.setText(QtGui.QApplication.translate("MainWindow", "Hydrogen Bond Donors ±", None, QtGui.QApplication.UnicodeUTF8))
        self.molecularWeightLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference in molecular weight between the active ligand and its respective decoys. When set to 0, decoys must have the exact same molecular weight in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.molecularWeightLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference in molecular weight between the active ligand and its respective decoys. When set to 0, decoys must have the exact same molecular weight in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.molecularWeightLabel.setText(QtGui.QApplication.translate("MainWindow", "Molecular weight ±", None, QtGui.QApplication.UnicodeUTF8))
        self.molwtBox.setSuffix(QtGui.QApplication.translate("MainWindow", " Da", None, QtGui.QApplication.UnicodeUTF8))
        self.rtotationalBondsLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of rotational bonds of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of rotational bonds in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.rtotationalBondsLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between the number of rotational bonds of the active ligand and its respective decoys. When set to 0, decoys must have the exact same number of rotational bonds in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.rtotationalBondsLabel.setText(QtGui.QApplication.translate("MainWindow", "Rotational bonds ±", None, QtGui.QApplication.UnicodeUTF8))
        self.clogPLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between active ligand\'s logP value and the logP values of its respective decoys. When set to 0, decoys must have the exact same logP value in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.clogPLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Sets the maximum difference between active ligand\'s logP value and the logP values of its respective decoys. When set to 0, decoys must have the exact same logP value in order to be accepted.", None, QtGui.QApplication.UnicodeUTF8))
        self.clogPLabel.setText(QtGui.QApplication.translate("MainWindow", "Octanol-water partition coefficient (logP) ±", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumDecoysPerActiveLigandLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "After finding this many decoys for a given active ligand, decoy search for that ligand will stop. \n"
"\n"
"If set to 0, there is no upper limit in the number of decoys per active ligand to find.", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumDecoysPerActiveLigandLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "After finding this many decoys for a given active ligand, decoy search for that ligand will stop. \n"
"\n"
"If set to 0, there is no upper limit in the number of decoys per active ligand to find.", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumDecoysPerActiveLigandLabel.setText(QtGui.QApplication.translate("MainWindow", "Maximum decoys per active ligand", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyLimitLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Decoy search will not stop until this many decoys have been found for each ligand or the decoy sources have been completely parsed.\n"
"\n"
"If set to 0, the search will not stop until the above maximum number of decoys has been found for all active ligands (if the maximum is set to other than 0) or all decoy sources have been completely parsed.", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyLimitLabel.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Decoy search will not stop until this many decoys have been found for each ligand or the decoy sources have been completely parsed.\n"
"\n"
"If set to 0, the search will not stop until the above maximum number of decoys has been found for all active ligands (if the maximum is set to other than 0) or all decoy sources have been completely parsed.", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyLimitLabel.setText(QtGui.QApplication.translate("MainWindow", "Minimum decoys per active ligand:", None, QtGui.QApplication.UnicodeUTF8))
        self.decoyMinSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Limit how many decoys to find for each ligand. If the limit is 0, there is no limit.", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheButton.setToolTip(QtGui.QApplication.translate("MainWindow", "This is the directory where temporary ZINC files will be downloaded.\n"
"They will be kept here if the \'Use cache\' option is enabled, otherwise they will be removed after they have been parsed.\n"
"\n"
"If the \'Use cache\' option is enabled, it is recommended to place the cache directory in a filesystem with 20+ Gb of free space.", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is the directory where temporary ZINC files will be downloaded.\n"
"They will be kept here if the \'Use cache\' option is enabled, otherwise they will be removed after they have been parsed.\n"
"\n"
"If the \'Use cache\' option is enabled, it is recommended to place the cache directory in a filesystem with 20+ Gb of free space.", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheButton.setText(QtGui.QApplication.translate("MainWindow", "Caché directory", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Load default values for all options", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Load default values for all options", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsButton.setText(QtGui.QApplication.translate("MainWindow", "Load Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Clears all items from all lists and tables", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Clears all items from all lists and tables", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Interrupt the current search. Decoys found so far will be saved in the output file. The search can be resumed by selecting the same active ligand files and decoy sources, plus enabling the \'Add new decoys option\' at the top of this tab and adding the interrupted search output file to the existing decoy files list.", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Interrupt the current search. Decoys found so far will be saved in the output file. The search can be resumed by selecting the same active ligand files and decoy sources, plus enabling the \'Add new decoys option\' at the top of this tab and adding the interrupted search output file to the existing decoy files list.", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.findDecoysButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Start the search. Depending on the options set and the decoy sources chosen, this can take some time.", None, QtGui.QApplication.UnicodeUTF8))
        self.findDecoysButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Start the search. Depending on the options set and the decoy sources chosen, this can take some time.", None, QtGui.QApplication.UnicodeUTF8))
        self.findDecoysButton.setText(QtGui.QApplication.translate("MainWindow", "Find decoys", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%v decoys found", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "DecoyFinder Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About DecoyFinder", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

