#!/bin/sh
VERSION=1.0
./distgeneric.sh
rm -r deb/opt/*
cp -r generic deb/opt/DecoyFinder

sudo chown -R root:root deb/*
sudo chmod -R o+rx-w deb/*

sudo dpkg --build deb decoyfinder-${VERSION}_all.deb

sudo chmod 777 *.deb

sudo chmod -R a+rw deb/* 

rm -r deb/opt/*
